### PR TITLE
Post for 0.8.4 release

### PR DESCRIPTION
**Pull request by nsubiron**
This change is [Reviewable](https://reviewable.io/reviews/carla-simulator/carla-simulator.github.io/13)

### CODE REVIEW

**Comment by felipecode** [comment]
Review status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @nsubiron and @felipecode)

---

*[_posts/2018-06-15-release-0.8.4.md, line 16 at r1](https://reviewable.io/reviews/carla-simulator/carla-simulator.github.io/13#-LF2KxyXDGg-c1dKcnju:-LF2KxyXDGg-c1dKcnjv:bok96a0) ([raw file](https://github.com/carla-simulator/carla-simulator.github.io/blob/93a50169c83b6990b34d4d7637b657ec077c86ab/_posts/2018-06-15-release-0.8.4.md#L16)):*
> ```Markdown
> {% include release_button.html release_tag="0.8.4" %}
> 
> Thanks to @minhaoxu1995 for catching something very obvious we missed, the new
> ```

that we missed ? 

---

*[_posts/2018-06-15-release-0.8.4.md, line 24 at r1](https://reviewable.io/reviews/carla-simulator/carla-simulator.github.io/13#-LF2LEE8C-2KHC0VDLcn:-LF2LEE8C-2KHC0VDLco:bc3ozz1) ([raw file](https://github.com/carla-simulator/carla-simulator.github.io/blob/93a50169c83b6990b34d4d7637b657ec077c86ab/_posts/2018-06-15-release-0.8.4.md#L24)):*
> ```Markdown
> we are aware they still cause issues when running long episodes, so we added a
> method to disable two-wheeled vehicles altogether. This can be done by adding to
> your _"CarlaSettings.ini"_ the following
> ```

the following:

---

*[_posts/2018-06-15-release-0.8.4.md, line 37 at r1](https://reviewable.io/reviews/carla-simulator/carla-simulator.github.io/13#-LF2LPMQDfE-ld_3_J8w:-LF2LPMQDfE-ld_3_J8x:bdmt9vm) ([raw file](https://github.com/carla-simulator/carla-simulator.github.io/blob/93a50169c83b6990b34d4d7637b657ec077c86ab/_posts/2018-06-15-release-0.8.4.md#L37)):*
> ```Markdown
> ###### New vehicle model
> 
> And since we are making a new release, we took the chance to add the latest
> ```

Finally, since

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla-simulator.github.io/13)*

**Comment by nsubiron** [comment]
Review status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @nsubiron and @felipecode)

---

*[_posts/2018-06-15-release-0.8.4.md, line 16 at r1](https://reviewable.io/reviews/carla-simulator/carla-simulator.github.io/13#-LF2KxyXDGg-c1dKcnju:-LF2Ql5nA9tsa1_-TvIy:b-ffreo5) ([raw file](https://github.com/carla-simulator/carla-simulator.github.io/blob/93a50169c83b6990b34d4d7637b657ec077c86ab/_posts/2018-06-15-release-0.8.4.md#L16)):*
<details><summary><i>Previously, felipecode (Felipe Codevilla) wrote…</i></summary><blockquote>

that we missed ? 
</blockquote></details>

what do you mean?

---

*[_posts/2018-06-15-release-0.8.4.md, line 24 at r1](https://reviewable.io/reviews/carla-simulator/carla-simulator.github.io/13#-LF2LEE8C-2KHC0VDLcn:-LF2RkOD-GK88z5xkMQi:b-896fix) ([raw file](https://github.com/carla-simulator/carla-simulator.github.io/blob/93a50169c83b6990b34d4d7637b657ec077c86ab/_posts/2018-06-15-release-0.8.4.md#L24)):*
<details><summary><i>Previously, felipecode (Felipe Codevilla) wrote…</i></summary><blockquote>

the following:
</blockquote></details>

Done.

---

*[_posts/2018-06-15-release-0.8.4.md, line 37 at r1](https://reviewable.io/reviews/carla-simulator/carla-simulator.github.io/13#-LF2LPMQDfE-ld_3_J8w:-LF2Rkqw6-wDJhWQY1b9:b-896fix) ([raw file](https://github.com/carla-simulator/carla-simulator.github.io/blob/93a50169c83b6990b34d4d7637b657ec077c86ab/_posts/2018-06-15-release-0.8.4.md#L37)):*
<details><summary><i>Previously, felipecode (Felipe Codevilla) wrote…</i></summary><blockquote>

Finally, since
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla-simulator.github.io/13)*

**Comment by felipecode** [comment]
Review status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @felipecode)

---

*[_posts/2018-06-15-release-0.8.4.md, line 16 at r1](https://reviewable.io/reviews/carla-simulator/carla-simulator.github.io/13#-LF2KxyXDGg-c1dKcnju:-LF2T5oV-RQ2bwDQfwSX:bzdm3jy) ([raw file](https://github.com/carla-simulator/carla-simulator.github.io/blob/93a50169c83b6990b34d4d7637b657ec077c86ab/_posts/2018-06-15-release-0.8.4.md#L16)):*
<details><summary><i>Previously, nsubiron (Néstor Subirón) wrote…</i></summary><blockquote>

what do you mean?
</blockquote></details>

forget.  I think it can go without " that". But I would end the sentence here  "very obvious we missed. The new ..."

---


*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla-simulator.github.io/13)*

**Comment by felipecode** [comment]
Reviewed 2 of 3 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/carla-simulator/carla-simulator.github.io/13)*

**Pull request merged**
